### ISSUE TITLE
Libmatio dependency

### ISSUE THREAD

**Issue by mees** [shubhtuls/drc#1]
There is a dependency with libmatio that is not mentioned.
To solve it:
sudo apt-get install libmatio2
luarocks install matio

Error:
$ gpu=1 th synthetic/evalScripts.lua | bash
/home/meeso/torch/install/bin/luajit: /home/meeso/torch/install/share/lua/5.1/trepl/init.lua:389: module 'matio' not found:No LuaRocks module found for matio
	no field package.preload['matio']
	no file '/home/meeso/.luarocks/share/lua/5.1/matio.lua'
	no file '/home/meeso/.luarocks/share/lua/5.1/matio/init.lua'
	no file '/home/meeso/torch/install/share/lua/5.1/matio.lua'
	no file '/home/meeso/torch/install/share/lua/5.1/matio/init.lua'
	no file '/usr/share/lua/5.1/matio.lua'
	no file '/usr/share/lua/5.1/matio/init.lua'
	no file './matio.lua'
	no file '/home/meeso/.luarocks/lib/lua/5.1/matio.so'
	no file '/home/meeso/torch/install/lib/lua/5.1/matio.so'
	no file '/home/meeso/torch/install/lib/matio.so'
	no file '/usr/lib/lua/5.1/matio.so'
	no file './matio.so'
	no file '/usr/local/lib/lua/5.1/matio.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:

**Comment by mees** [comment]
JSON seems also needed for the pascal evaluation:
luarocks install json

**Comment by shubhtuls** [comment]
Thanks, I'll add these to the README (I'd forgotten that these were not a part of the basic torch install).
