### ISSUE TITLE
Invalid download link for annotations for segmentation masks

### ISSUE THREAD

**Issue by bomb2peng** [shubhtuls/drc#10]
Hi Dr. Shubham,

It seems the download link for segmentation masks of VOC 3D+ dataset is invalid. Could you please provide a new download link?

**Comment by shubhtuls** [comment]
Hi,
Apologies for the inactive link. [Here](https://www.dropbox.com/s/uobv3q9gmbxq0v5/pascalData.tar.gz?dl=0) is a copy. 

Thanks!
