### ISSUE TITLE
Problems evaluating Pascal

### ISSUE THREAD

**Issue by mees** [shubhtuls/drc#2]
Hi,
I have problems evaluating Pascal, seems like I missed some download. When I run the evaluation I get nil values in the matlab script (see attachment). It is also unclear how I should change the paths in https://github.com/shubhtuls/drc/blob/master/preprocess/pascal/startup.m
as in the tars there was no PASCAL3D folder I believe.
When I try to compute the ortographic cam I get:
>> classes = {'aeroplane','car','chair'};
>> for c=1:3
    computeOrthographicCam(classes{c});
 computeOrthographicCamImagenet(classes{c});
end
Error using load
Unable to read file '/home/meeso/drc/cachedir/Datasets/PASCAL3D/Annotations/aeroplane_pascal/2008_000021'. No such file or directory.

Error in extractPascalAnnotations (line 9)
        load(fullfile(annoDir,voc_image_id));

Error in computeOrthographicCam (line 3)
    pascalInstances = extractPascalAnnotations(className);

[drc_pascal_error.txt](https://github.com/shubhtuls/drc/files/1121876/drc_pascal_error.txt)

**Comment by shubhtuls** [comment]
PASCAL3D (V1.1) is another dataset which needs to be downloaded from [here](http://cvgl.stanford.edu/projects/pascal3d.html). You'll also need the PASCAL VOC dataset from [here](http://host.robots.ox.ac.uk/pascal/VOC/) and edit the paths in startup to point to these.

I am sorry the instructions were not more explicit about this.

**Comment by shubhtuls** [comment]
Updated the [PASCAL instructions](https://github.com/shubhtuls/drc/blob/master/docs/pascal.md) accordingly.
