### ISSUE TITLE
Matlab Aerospace Toolbox dependency

### ISSUE THREAD

**Issue by mees** [shubhtuls/drc#3]
When preprocessing the datasets with
`classes = {'aeroplane','car','chair'};
for c=1:3
    computeOrthographicCam(classes{c});
    computeOrthographicCamImagenet(classes{c});
end
precomputeVoxelsP3d;`

one gets an error, if the Matlab Aerospace toolbox is not installed:

`Undefined function or variable angle2dcm.
Error in extractPascalAnnotations>viewpointToRots (line 49)
    R = angle2dcm(pi-euler(1), -pi/2 + euler(2), euler(3),'ZXZ'); %empirically computed
Error in extractPascalAnnotations (line 26)
        [rot,euler]=viewpointToRots(viewpoint);
Error in computeOrthographicCam (line 3)
    pascalInstances = extractPascalAnnotations(className);`

**Comment by shubhtuls** [comment]
There are some online implementations of the angle2dcm function which you can use instead if the aerospace toolbox is not available e.g. [here](https://github.com/su2code/MeshTools/blob/master/Matlab/angle2dcm.m).

**Comment by mees** [comment]
I guess you should either include an implementation or mention in the docs that there is this aerospace toolbox dependency.

**Comment by shubhtuls** [comment]
Thanks for the suggestion - I'll mention this as a dependency.
