### ISSUE TITLE
Problems in Run Demos and Eval. Pascal and ShapeNet

### ISSUE THREAD

**Issue by chaoer** [shubhtuls/drc#6]
Hi,

When I tried the [demo.ipynb](https://github.com/shubhtuls/drc/blob/master/demo/demo.ipynb), it reports that cannot find [pascal,shapenet]_pred.png.  In this code, it indeed did not save the *_pred.png . But unfortunately I'm not familiar with lua, could you please tell me how should i save this file?
And there are some more questions:
1. Is there any predict script which can reconstruct from a single input image ?

2. In your paper 2017  [Hierarchical Surface Prediction for 3D Object Reconstruction](https://arxiv.org/pdf/1704.00710.pdf), the resolution of predicted geometry increased along the increment of voxel side length. And in the script [reconstructionBenchmark.lua](https://github.com/shubhtuls/drc/blob/master/benchmark/synthetic/reconstructionBenchmark.lua), it has param of grid size. 
   So I was wondering whether the grid size will influence the resolution of predicted geometry. (Will the param of `image size` also influence the resolution ?).  If it's true, can i simple change this parameter to 64, 128 and so on to get a geometry with higer resolution using your provided pre-model ? (I am now struggling with downloading those two big datasets and thus cannot directly try this by changing the param in your script.  So could you please give me a theoretical answer.)

3. In the [DRC](https://arxiv.org/pdf/1704.06254.pdf) paper, you provided results of _3D Scene Recongstruction from Ego-motion_ in **Section 5.3** and _Object Reconstruction from RGB Supervision_ in **Section 5.4**. 
Could you please tell me which script in this repo.  can reproduce these two baseline ?

**Comment by shubhtuls** [comment]
Hi @chaoer ,
0. Did you change the path to blender in the line 1 of the demo file?
1. The demo notebook is precisely supposed to show the steps for this - please see it for steps on how to load the network and use it for a new image.
2. We have released the code for the paper you mention in a separate github repo, and it'd be great if you could create this issue in that repo instead of this, as Christian might be able to help.
3. Unfortunately, we did not have scripts for these experiments are these were only meant for qualitative demonstrations. However, there is an external repo which implements the training we describe in Sec 5.4 (https://github.com/arnabgho/color-drc), so you might find that helpful.

**Comment by chaoer** [comment]
@shubhtuls 
Thanks for your kindly reply.

0.  I had already changed the path of blender to where it installed. And the demo file results reports that cannot find [pascal,shapenet]_pred.png.
I am not sure where the **_pred.png** was saved to disk. (I only find a sentence for saving the **_preg.obj)**, but there was no code for saving **_pred.png** in the demo file.

1. Yes, I'll follow the demo file to write a predict script;

2. I have search through your and Christian' web page, github. But I cannot find this repo. Could you please give me a web link?

3. I'll give a try of this color-drc. Thanks a lot.

**Comment by shubhtuls** [comment]
0. The second-last line in cell 6 of demo.ipynb is the one that renders and save the image:
```
demoUtil.renderMesh(blenderExec, blendFile, predMesh, predPng)
```
Perhaps you can look at the renderMesh function in more detail to debug why it fails for you.

2. https://github.com/chaene/hsp

**Comment by chaoer** [comment]
@shubhtuls 
Thanks a lot. This do me a big favor.

**Comment by chaoer** [comment]
@shubhtuls 
Sorry for bothering again.

I know I should create an issue under the hsp repo. However, the owner of that repo. did not answer me.

When I tried to train hsp, the file format conversion stuck me.

The script under preprocess of your repo. can do part of the conversion. But there are two `Pyramid` and `Voxels` data that I don't know how to obtain from the `obj` file. 
Do you have any suggestions ?

Moreover, the rendered png `(render_{}.png)` from [renderPreprocessShapenet](https://github.com/shubhtuls/drc/blob/master/preprocess/synthetic/rendering/renderPreprocessShapenet.py) is empty. Is there any settings I should modify to avoid this?
