### ISSUE TITLE
Pre-trainded models for Pascal3D and ShapeNet

### ISSUE THREAD

**Issue by ashwinpathak20** [shubhtuls/drc#9]
Can you please provide a working link to the pre-trained models. The provided link is not working.

**Comment by shubhtuls** [comment]
Hi,
Apologies for the missing link. [Here](https://www.dropbox.com/sh/7rvqyoaqf9udod9/AACV9c7meLHtMi8rAjiJPeH7a?dl=0) is a copy. Please let me know if anything else might help.
